---
- name: Allow traffic through loopback interface
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Drop invalid  connections
  iptables:
    chain: INPUT
    ctstate: INVALID
    jump: DROP

- name: Allow new packets on SSH for Vagrant Host
  iptables:
    chain: INPUT
    protocol: tcp
    in_interface: enp0s3
    destination_port: 22
    ctstate: NEW
    jump: ACCEPT

- name: Allow new packets on SSH
  iptables:
    chain: INPUT
    protocol: tcp
    in_interface: enp0s8
    destination_port: 22
    ctstate: NEW
    jump: ACCEPT

- name: Allow node exporter traffic from prometheus server
  iptables:
    chain: INPUT
    in_interface: enp0s8
    source: "{{ hostvars['monitoring'].ansible_host }}"
    protocol: tcp
    destination_port: 9100
    jump: ACCEPT

- name: Allow traffic to -Grafana- service
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 3000
    jump: ACCEPT

- name: Allow traffic to -Prometheus- service
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 9090
    jump: ACCEPT

- name: Allow traffic to -Alertmanager- service
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_ports: "9093:9094"
    jump: ACCEPT

- name: Allow traffic to elasticsearch
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 9200
    jump: ACCEPT

- name: Allow traffic to kibana
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 5601
    jump: ACCEPT

- name: Allow traffic to logstash
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 5044
    jump: ACCEPT

- name: Allow ICMP
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: Set the policy for the INPUT chain to DROP
  iptables:
    chain: INPUT
    policy: DROP
...