---
- name: Installing MySQL server and other soft
  apt:
    name:
      - mysql-server
      - python3-pip
      - sshpass
    state: present
    update_cache: yes

- name: Installing additional Python packet - PyMySQL
  pip:
    name: PyMySQL

- name: Statring MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Clear old MySQL configuration file
  file:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    state: absent

- name: Copying configuration file to Master server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "files/mysqld_master.cnf", dest: "/etc/mysql/mysql.conf.d/mysql.cnf" }
    - { src: "files/mysqldump.cnf", dest: "/etc/mysql/conf.d/mysqldump.cnf" }
  notify:
    - Restart MySQL  

- name: Generating .my.cnf file on Master server
  shell: "echo \"[mysql]\nuser='root'\npassword='{{ mysql_root_pass }}'\n\" > /root/.my.cnf"
  args:
    creates: /root/.my.cnf
  notify: 
    - Restart MySQL

- name: Setting up root password on MySQL service
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_pass }}"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
    update_password: on_create
  notify:
    - Restart MySQL

- name: Creating database -wpress_db-
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: wpress_db
    state: present

- name: Creating wordpress user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: wp_user
    password: "{{ mysql_wp_pass }}"
    host: '%'
    priv: 'wpress_db.*:ALL'

- name: Creating replication user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: repl
    password: "{{ mysql_user_pass }}"
    host: '%'
    priv: '*.*:REPLICATION SLAVE'

- name: Copying DB dump 
  copy:
    src: "{{ path_to_master_dump }}"
    dest: /tmp/master.sql

- name: Loading DB dump
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: all
    state: import
    target: /tmp/master.sql

- name: Deleting DB dump
  file:
    path: /tmp/master.sql
    state: absent

#- name: Creating new dump of -wpress_db- database with necessary tables
#  shell: mysqldump --all-databases --add-drop-table --create-options --disable-keys \ 
#                   --extended-insert --single-transaction --quick --events --routines \
#                   --set-gtid-purged=OFF --triggers --source-data=0 --skip-lock-tables \
#                   --flush-privileges \
#                   -u root -p{{ mysql_root_pass }} > /home/vagrant/master.sql

- name: Restart MySQL
  meta: flush_handlers

- name: Congigure iptables
  import_tasks: firewall.yml
...
